services:
  golang_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang_api
    container_name: golang_api
    ports:
      - "8080:8080"
    volumes:
      - volume:/app/data

volumes:
  volume:

